#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.

IP="${1}"
fileN=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ];
then
	echo "Usage: ${fileN} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
